### ISSUE TITLE
福来客栈 样式表

### ISSUE THREAD

**Issue by yozman** [yozman/flyinn#8]
`style.css`

```css
.x {
	float: left;
	line-height: inherit;
}
.x:last-child {
	float: right;
}
.y {
	margin-left: auto;
	margin-right: auto;
	max-width: 960px;
	position: relative;
}
.y:after {
	clear: both;
	content: '';
	display: table;
}
.z {
	position: absolute;
}
* {
	box-sizing: border-box;
}
a {
	color: inherit;
	cursor: pointer;
	display: block;
	text-decoration: none;
}
body {
	font-size: 12px;
	line-height: 1;
	margin: 0;
	overflow: hidden;
}
html {
	-webkit-user-select: none;
}
iframe {
	border: none;
	height: 100%;
	width: 100%;
}
img {
	vertical-align: middle;
}
ul {
	list-style: none;
	margin: 0;
	padding-left: 0;
}
```
